language: python
python:
- '2.7'
install:
- pip install -U setuptools
script:
- python setup.py install
deploy:
  provider: pypi
  user: Robert.Elwell
  password:
    secure: B0ldeQFtin0vMi8p9qYLoeb8Sbruc66RCd0bM/g7ID6LhlmCowXsX0x+4h6HtlZixfGjMA7XaQfPA+YFR79c4iC0hM63OxyEWlK2H70t3DZkO9xu1QgkawQVInEd6k3LfI4MKVOqdubVTv2xe+7b27/JVA38VmU6sQG7MGWOWNc=
  on:
    distributions: sdist bdist_wheel
    repo: solrcloudpy/solrcloudpy
